### ISSUE TITLE
Is it possible to add a marker on more then one address?

### ISSUE THREAD

**Issue by hardcoredevelopment** [jmelosegui/GooglemapMvc#26]
Hello

Is it possible to add a marker on more then one address?

 @(Html.GoogleMap()
        .Name("map")
                .Center(c => c.Address("broadway 1 new york"))                   
        .Markers(m => m.Add()));

**Comment by jmelosegui** [comment]
Hi, 

Today Geo Location Services only works at the map level.
To fulfill your requirement I need to add that feature to the markers.

**Comment by jmelosegui** [comment]
Hi @hardcoredevelopment, 

Just committed my first attempt to load markers using Geocoding. This is a tricky one due to the google API [limits](https://developers.google.com/maps/documentation/geocoding/#Limits).

I hope to come up with the final solution any time during the next week. In the meantime you can download the dev branch and try this initial version. 

I also created the [markers geocoding sample](http://localhost/Jmelosegui.Mvc.Googlemap.Examples/marker/Geocoding) so you can see this feature in action.

**Comment by jmelosegui** [comment]
Hi, 
In the dev branch you will a complete solution to your request. Please let mi know your thoughts.
I will continue with some more testing and if everything is OK I will release a new version of the nuget package over the weekend.
