### ISSUE TITLE
outside map event trigger marker

### ISSUE THREAD

**Issue by jmingli** [jmelosegui/GooglemapMvc#35]
Hi Juan,

First, your project made our life so much easier!.

I got a question, like yelp.com how can I make an outside of the google map event trigger the marker on the map? any sample code would help a lot

http://screencast.com/t/evi08pijr

Thank you.

**Comment by jmelosegui** [comment]
Hi @jmingli

That is a very interesting feature. Unfortunately I can not see an easy solution right now because I don't save the reference to the markers and therefore you cannot access to the markers collection out side the control.

In this moment I am working on the "layers feature" specifically on issue #29. After that one I will be glad to implement your request.

Thank for your feedback.

**Comment by jmelosegui** [comment]
Hi @jmingli 

I just pushed the changes to allow access to the markers collection from outside the map.

Please review the sample [ExternalReference](http://www.jmelosegui.com/map/marker/ExternalReference) for more info.

The changes are in the dev branch. please download the latest changes and let me know your thought.

**Comment by jmingli** [comment]
Juan,

Great, Thank you.

-Ming.
