### ISSUE TITLE
Default map center

### ISSUE THREAD

**Issue by btidoug** [jmelosegui/GooglemapMvc#40]
I am using marker clustering and have the map set to center based on the marker boundaries.  Works great.  How can I set a default "center of map" if my view happens to not have any markers.  Right now it centers around florida and cuba.

If I use the .center feature, how does that work when using "fit to marker bounds"?

**Comment by jmelosegui** [comment]
You should use something like:

```
 @(Html.GoogleMap()
                .Name("map")
                .Center(c => c.Latitude(40)
                                .Longitude(-3))
                .Height(420)
                .FitToMarkersBounds((bool)ViewData["FitToMarkersBounds"])
                .MarkersGeocoding(true)
                .Markers(m =>
                {
                  ...............
                })
        )
```
Then if your marker collection is not empty, the center of the map is calculated using the average of the markers coordinates, otherwise the center will be the one you set up using the _Center_ method of the _GoogleMap_ helper.

You can see all of this in action in [this](http://www.jmelosegui.com/map/marker/FitToMarkersBounds) sample.
