### ISSUE TITLE
Marker Title cannot be a variable

### ISSUE THREAD

**Issue by lordofscripts** [jmelosegui/GooglemapMvc#81]
I am following your Geolocation example but I noticed a strange problem with it. First, I am NOT using the UseYourLocation, rather I am using my own latitude/longitude inside Center() where both coordinate values come from ViewBag.Lat and ViewBag.Lon respectively and I see the marker is properly placed.

But further down on the same example a marker is created with a title. I noticed that if I use a constant string as you have  like "Hello Geolocation" or "your company" it works fine, it is shown as a tooltip on the map. But if  replace that with a valid ViewBag variable such as ViewBag.MyHome then a bunch of red zigzag lines appear on the VS view (the .CSHTML file)  and the following error is produced on the line AFTER the title (on the .Window line)

Cannot use a lambda expression as an argument to a dynamically dispatched operation without first casting it to a delegate or expression tree type

For me I would prefer fetching all the marker information from a service (API call for example or JSON action on the controller) and filling that in on the map.

**Comment by jmelosegui** [comment]
I don´t think I clearly understand your problems, but I will do my best to answer you.

>  First, I am NOT using the UseYourLocation, rather I am using my own latitude/longitude inside Center() where both coordinate values come from ViewBag.Lat and ViewBag

As the online sample states. If you use the option `UseYourLocation` along with the `Latitude` and `Longitude` from the `Center` helper method, the marker will be placed at your current location if your browser supports Geolocation and you have allowed the location sharing, otherwise it is placed in the map default location. So I for the issue I can only think that your `ViewBag.Lat` and `ViewBag.Lon` are matching your current location and that is why seems the marker is "properly placed".

For your second issue

> Cannot use a lambda expression as an argument to a dynamically dispatched operation without first casting it to a delegate or expression tree type

The compiler is clear enough and is also giving you a solution. So writing something like this for your marker title will work.

```csharp
...
.Title(ViewBag.Title as string) 
...
```

Regarding your preferences:

>For me I would prefer fetching all the marker information from a service (API call for example or JSON action on the controller) and filling that in on the map.

This control allows you use an `IEnumerable<T>` as datasouce to databind the marker properties to any property from your `T` object regardless the source of your data (ie. API Call, Database, File System, etc ) as long as you can create an `IEnumerable<T>`. For more info on this subject see the [this sample](http://www.jmelosegui.com/map/marker/DataBindingToModel)

**Comment by lordofscripts** [comment]
As I said I omitted the "UseYourLocation" call and only had Lat/Lon and it was properly placed in the configured location, I know because I first tried without it and it took me to some location in Europe and if I used "UseYourLocation" it centered on the center of the city rather than my location so that is working well.

Somehow I didn't get that message well indeed, thank you for the clarification and patience, now it is working as expected with the "as string" and the Title shows as Tooltip.

Up to a couple of years ago I used GMap3() adapted to MVC which was quite versatile but at some point it just misbehaved a lot and support vanished. Then I cooked my own GoogleMap implementation for MVC which fitted MY limited requirements and more, but on this new app experiment I decided to try yours which I found by accident. I must say I like it a lot, it is really elegant and with a lot of features. Thank you for sharing your project and keep up the good work.
